### ISSUE TITLE
Can't resolve "require('tripwire')" properly with iisnode

### ISSUE THREAD

**Issue by joshburgess** [tjanczuk/tripwire#10]
I'm getting the following error when trying to use this with iisnode to guard against processes hanging up:

Application has thrown an uncaught exception and is terminated:
Error: The specified procedure could not be found.

\?\C:\Sites\subdomain.domain.com\node_modules\tripwire\lib\native\win32\0.10\x64\tripwire.node
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Sites\subdomain.domain.com\node_modules\tripwire\lib\tripwire.js:14:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

Any ideas?

**Comment by shlomisas** [comment]
+1

**Comment by kristianoye** [comment]
I had this problem too.  I don't know what version of Windows the npm binaries are targeting but they did not work on my x64 Windows 10 box.  I recompiled the native binaries and it worked (although not quite as I was hoping... was hoping I could recover after the exception but apparently it just keeps throwing exceptions until I recycle the code)?)

**Comment by kristianoye** [comment]
V8 has an isolate method named CancelTerminateExecution().  It seems like this could be used to resume the thread after it is terminated.

**Comment by arpit-systango** [comment]
Any solutions on this error, getting the same issue on windows 10.
