### ISSUE TITLE
Doesn't work with Node 4 LTS

### ISSUE THREAD

**Issue by rpaterson** [tjanczuk/tripwire#9]
Tripwire doesn't seem to work properly with the latest Node 4 LTS (v4.2.4).  The example in the README:
```Javascript
process.on('uncaughtException', function (e) {
  console.log('The event loop was blocked for longer than 2000 milliseconds');
  process.exit(1);
});

// set the limit of execution time to 2000 milliseconds
tripwire.resetTripwire(2000);

// execute code that will block the event loop for longer
while(true);

// clear the tripwire (in this case this code is never reached)
tripwire.clearTripwire();
```

In Node v0.10 it pauses for 2 seconds and then prints `The event loop was blocked for longer than 2000 milliseconds` to the console before exiting.  In Node v4.2.4 it pauses and then exits without printing anything.

In other more complicated examples sometimes I get unexpectedException: 
```
Error: Blocked event loop.
    at Error (native)
    at processImmediate [as _immediateCallback] (timers.js:367:26)
```
... or ...
```
TypeError: immediate._onImmediate is not a function
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by rpaterson** [comment]
Note when the process exits the exit code is `0`.

**Comment by rpaterson** [comment]
(I'm on Linux)

**Comment by rpaterson** [comment]
/samples/sample_exceptions.js and /samples/sample_perpertuum_mobile.js _do_ work, but /samples/sample_sandboxing.js does not - it prints only `[Malcolm] Ha ha ha! I am taking over your event loop, Albert. Ha ha ha!` and then exits with exit code `0`.
